pluginName=Git Flow Ops UI
providerName=Git Flow Ops Contributors
menu.main.label=Git Flow Ops
menu.more.label=More Git Actions
view.operations.name=Git
command.openView.name=Open Git Panel
command.hello.name=About Git Flow Ops
command.quickStash.name=Quick Stash
command.quickPop.name=Restore Last Stash
command.smartPull.name=Pull
command.smartPush.name=Push
command.smartPull.teamLabel=Pull (Git Flow Ops)
command.smartPush.teamLabel=Push (Git Flow Ops)
command.pullAll.name=Pull All Repositories
command.smartCheckout.name=Smart Checkout...
command.undoLastCommit.name=Undo Last Commit...
command.commitToNewBranch.name=Commit to New Branch...
command.moveLastCommit.name=Move Last Commit to Branch...
command.safeCommit.name=Safe Commit...
command.generateMessage.name=Generate Commit Message
command.openFile.name=Open File in Browser
command.openBranch.name=Open Branch in Browser
command.openCommit.name=Open Commit in Browser
