pluginName=Git Flow Ops UI
providerName=Git Flow Ops Contributors
menu.main.label=Git Flow Ops
command.hello.name=About Git Flow Ops
command.quickStash.name=Quick Stash
command.quickPop.name=Restore Last Stash
